#!/usr/bin/env python3
"""
Generate C++ header file from TOML display configuration
Converts .config files to DisplayConfig.h for compile-time Arduino configuration
"""

import sys
import argparse
from pathlib import Path
from datetime import datetime

try:
    from st7735_tools.config_loader import load_display_config
except ImportError:
    print("Error: st7735_tools.config_loader not found")
    sys.exit(1)


def generate_header(config, output_file='include/DisplayConfig.h'):
    """
    Generate C++ header file from display configuration
    
    Args:
        config: DisplayConfig object
        output_file: Path to output header file
    """
    
    # Calculate orientation rotation value
    orientation_map = {
        'landscape': 1,
        'portrait': 0,
        'reverse_landscape': 3,
        'reverse_portrait': 2
    }
    rotation = orientation_map.get(config.orientation, 1)
    
    # Generate header content
    header_content = f"""/*
 * DisplayConfig.h
 * Auto-generated from {config.name}.config
 * Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
 * 
 * DO NOT EDIT THIS FILE MANUALLY!
 * Edit the .config file and regenerate using generate_config_header.py
 */

#ifndef DISPLAY_CONFIG_H
#define DISPLAY_CONFIG_H

// Device Information
#define DEVICE_NAME "{config.name}"
#define DEVICE_MANUFACTURER "{config.manufacturer}"
#define DEVICE_MODEL "{config.model}"

// Pin Assignments
#define TFT_CS     {config.pins['cs']}      // Chip Select
#define TFT_DC     {config.pins['dc']}     // Data/Command select
#define TFT_RST    {config.pins['rst']}     // Reset
#define TFT_BL     {config.pins['bl']}      // Backlight control

// Display Dimensions
#define DISPLAY_WIDTH  {config.width}
#define DISPLAY_HEIGHT {config.height}

// Display Orientation
#define DISPLAY_ROTATION {rotation}  // {config.orientation}

// Calibrated Usable Area
#define USABLE_ORIGIN_X {config.calibration['left']}
#define USABLE_ORIGIN_Y {config.calibration['top']}
#define USABLE_WIDTH   {config.usable_width}
#define USABLE_HEIGHT  {config.usable_height}

// Calibrated Center Point
#define CENTER_X {config.center[0]}
#define CENTER_Y {config.center[1]}

// Usable Bounds (for reference)
#define USABLE_LEFT   {config.calibration['left']}
#define USABLE_RIGHT  {config.calibration['right']}
#define USABLE_TOP    {config.calibration['top']}
#define USABLE_BOTTOM {config.calibration['bottom']}

#endif // DISPLAY_CONFIG_H
"""
    
    # Write to file
    output_path = Path(output_file)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    with open(output_path, 'w') as f:
        f.write(header_content)
    
    print(f"✓ Generated {output_file}")
    print(f"  Device: {config.name}")
    print(f"  Pins: CS={config.pins['cs']}, DC={config.pins['dc']}, RST={config.pins['rst']}, BL={config.pins['bl']}")
    print(f"  Usable: {config.usable_width}x{config.usable_height} @ ({config.calibration['left']},{config.calibration['top']})")
    print(f"  Orientation: {config.orientation} (rotation={rotation})")


def main():
    parser = argparse.ArgumentParser(
        description="Generate C++ header from display config file",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python3 generate_config_header.py DueLCD01.config
  python3 generate_config_header.py --device DueLCD02
  python3 generate_config_header.py --config DueLCD01.config --output include/MyDisplay.h
        """
    )
    
    parser.add_argument('config_file', nargs='?',
                       help='Path to config file (e.g., DueLCD01.config)')
    parser.add_argument('--device', '-d', type=str,
                       help='Device name (auto-finds config file)')
    parser.add_argument('--output', '-o', type=str, default='include/DisplayConfig.h',
                       help='Output header file path (default: include/DisplayConfig.h)')
    
    args = parser.parse_args()
    
    # Determine config file
    config_file = None
    if args.config_file:
        config_file = args.config_file
    elif args.device:
        # Look for device config
        config_file = f"{args.device}.config"
        if not Path(config_file).exists():
            print(f"Error: Config file '{config_file}' not found for device '{args.device}'")
            return 1
    else:
        print("Error: Please specify a config file or device name")
        parser.print_help()
        return 1
    
    # Load configuration
    try:
        config = load_display_config(config_file)
    except Exception as e:
        print(f"Error loading config: {e}")
        return 1
    
    # Generate header
    try:
        generate_header(config, args.output)
        return 0
    except Exception as e:
        print(f"Error generating header: {e}")
        return 1


if __name__ == '__main__':
    sys.exit(main())
