#!/usr/bin/env python3
"""
Generate DisplayConfig.h from .config files
Converts TOML display configuration files to C++ header for Arduino Due firmware
"""

import toml
from pathlib import Path
from datetime import datetime
import sys


def parse_config(config_file):
    """Parse a single .config file"""
    with open(config_file, 'r') as f:
        data = toml.load(f)
    
    # Extract values
    device = data['device']
    pinout = data['pinout']
    cal = data['calibration']
    
    return {
        'name': device['name'],
        'manufacturer': device.get('manufacturer', 'Unknown'),
        'model': device.get('model', 'Unknown'),
        'width': device['published_resolution'][0],
        'height': device['published_resolution'][1],
        'orientation': cal.get('orientation', 'landscape'),
        'rotation': 1 if cal.get('orientation', 'landscape') == 'landscape' else 0,
        'pins': pinout,
        'left': cal['left'],
        'right': cal['right'],
        'top': cal['top'],
        'bottom': cal['bottom'],
        'center': cal['center']
    }


def generate_header(configs):
    """Generate C++ header file content"""
    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    device_names = ', '.join([cfg['name'] for cfg in configs])
    
    lines = [
        '/*',
        ' * DisplayConfig.h - Multi-Display Configuration',
        ' * Auto-generated from all .config files',
        f' * Generated: {timestamp}',
        ' * ',
        ' * DO NOT EDIT THIS FILE MANUALLY!',
        ' * Edit the .config files and regenerate using generate_config_header.py',
        ' * ',
        f' * Registered displays: {device_names}',
        ' */',
        '',
        '#ifndef DISPLAY_CONFIG_H',
        '#define DISPLAY_CONFIG_H',
        '',
        '#include <Arduino.h>',
        '#include "DisplayManager.h"',
        '',
        '// Number of registered displays',
        f'#define NUM_DISPLAYS {len(configs)}',
        '',
        ''
    ]
    
    # Generate defines for each display
    for idx, cfg in enumerate(configs):
        name_upper = cfg['name'].upper()
        usable_width = cfg['right'] - cfg['left'] + 1
        usable_height = cfg['bottom'] - cfg['top'] + 1
        
        lines.extend([
            f'// ========== {cfg["name"]} ==========',
            f'#define {name_upper}_INDEX {idx}',
            '',
            '// Device Information',
            f'#define {name_upper}_NAME "{cfg["name"]}"',
            f'#define {name_upper}_MANUFACTURER "{cfg["manufacturer"]}"',
            f'#define {name_upper}_MODEL "{cfg["model"]}"',
            '',
            '// Pin Assignments',
            f'#define {name_upper}_TFT_CS {cfg["pins"]["cs"]}',
            f'#define {name_upper}_TFT_DC {cfg["pins"]["dc"]}',
            f'#define {name_upper}_TFT_RST {cfg["pins"]["rst"]}',
            f'#define {name_upper}_TFT_BL {cfg["pins"]["bl"]}',
            '',
            '// Display Dimensions',
            f'#define {name_upper}_DISPLAY_WIDTH {cfg["width"]}',
            f'#define {name_upper}_DISPLAY_HEIGHT {cfg["height"]}',
            f'#define {name_upper}_DISPLAY_ROTATION {cfg["rotation"]}',
            '',
            '// Calibrated Usable Area',
            f'#define {name_upper}_USABLE_ORIGIN_X {cfg["left"]}',
            f'#define {name_upper}_USABLE_ORIGIN_Y {cfg["top"]}',
            f'#define {name_upper}_USABLE_WIDTH {usable_width}',
            f'#define {name_upper}_USABLE_HEIGHT {usable_height}',
            '',
            '// Center Point',
            f'#define {name_upper}_CENTER_X {cfg["center"][0]}',
            f'#define {name_upper}_CENTER_Y {cfg["center"][1]}',
            '',
        ])
    
    # Generate initialization function
    lines.extend([
        '// Display Registry Initialization',
        'inline void initializeDisplayRegistry(DisplayManager& manager) {',
        ''
    ])
    
    for cfg in configs:
        name_upper = cfg['name'].upper()
        lines.extend([
            f'    // Add {cfg["name"]}',
            '    {',
            '        DisplayConfig cfg;',
            f'        cfg.name = {name_upper}_NAME;',
            f'        cfg.manufacturer = {name_upper}_MANUFACTURER;',
            f'        cfg.model = {name_upper}_MODEL;',
            f'        cfg.cs = {name_upper}_TFT_CS;',
            f'        cfg.dc = {name_upper}_TFT_DC;',
            f'        cfg.rst = {name_upper}_TFT_RST;',
            f'        cfg.bl = {name_upper}_TFT_BL;',
            f'        cfg.width = {name_upper}_DISPLAY_WIDTH;',
            f'        cfg.height = {name_upper}_DISPLAY_HEIGHT;',
            f'        cfg.rotation = {name_upper}_DISPLAY_ROTATION;',
            f'        cfg.usableX = {name_upper}_USABLE_ORIGIN_X;',
            f'        cfg.usableY = {name_upper}_USABLE_ORIGIN_Y;',
            f'        cfg.usableWidth = {name_upper}_USABLE_WIDTH;',
            f'        cfg.usableHeight = {name_upper}_USABLE_HEIGHT;',
            f'        cfg.centerX = {name_upper}_CENTER_X;',
            f'        cfg.centerY = {name_upper}_CENTER_Y;',
            '        manager.addDisplay(cfg);',
            '    }',
            ''
        ])
    
    lines.extend([
        '}',
        '',
        '#endif // DISPLAY_CONFIG_H'
    ])
    
    return '\n'.join(lines)


def main():
    """Main function"""
    # Find all .config files
    config_files = sorted(Path('.').glob('*.config'))
    
    if not config_files:
        print("ERROR: No .config files found in current directory")
        sys.exit(1)
    
    print(f"Found {len(config_files)} config file(s):")
    for cf in config_files:
        print(f"  - {cf.name}")
    
    # Parse all configs
    configs = []
    for cf in config_files:
        try:
            cfg = parse_config(cf)
            configs.append(cfg)
            print(f"✓ Parsed {cfg['name']}")
        except Exception as e:
            print(f"✗ Error parsing {cf.name}: {e}")
            sys.exit(1)
    
    # Generate header
    header_content = generate_header(configs)
    
    # Write to include/DisplayConfig.h
    output_file = Path('include/DisplayConfig.h')
    output_file.parent.mkdir(exist_ok=True)
    
    with open(output_file, 'w') as f:
        f.write(header_content)
    
    print(f"\n✓ Generated {output_file}")
    print(f"  Registered {len(configs)} display(s): {', '.join([c['name'] for c in configs])}")
    print("\nHeader file ready! Rebuild firmware to apply changes.")


if __name__ == '__main__':
    main()
