/*
 * DisplayConfig.h
 * Auto-generated from DueLCD02.config
 * Generated: 2025-11-06 01:11:03
 * 
 * DO NOT EDIT THIS FILE MANUALLY!
 * Edit the .config file and regenerate using generate_config_header.py
 */

#ifndef DISPLAY_CONFIG_H
#define DISPLAY_CONFIG_H

// Device Information
#define DEVICE_NAME "DueLCD02"
#define DEVICE_MANUFACTURER "Jessinie"
#define DEVICE_MODEL "n/a"

// Pin Assignments
#define TFT_CS     29      // Chip Select
#define TFT_DC     31     // Data/Command select
#define TFT_RST    33     // Reset
#define TFT_BL     35      // Backlight control

// Display Dimensions
#define DISPLAY_WIDTH  128
#define DISPLAY_HEIGHT 160

// Display Orientation
#define DISPLAY_ROTATION 0  // portrait

// Calibrated Usable Area
#define USABLE_ORIGIN_X 2
#define USABLE_ORIGIN_Y 1
#define USABLE_WIDTH   126
#define USABLE_HEIGHT  158

// Calibrated Center Point
#define CENTER_X 65
#define CENTER_Y 80

// Usable Bounds (for reference)
#define USABLE_LEFT   2
#define USABLE_RIGHT  127
#define USABLE_TOP    1
#define USABLE_BOTTOM 158

#endif // DISPLAY_CONFIG_H
