/*
 * DisplayConfig.h - Multi-Display Configuration
 * Auto-generated from all .config files
 * Generated: 2025-11-06 03:23:47
 * 
 * DO NOT EDIT THIS FILE MANUALLY!
 * Edit the .config files and regenerate using generate_config_header.py
 * 
 * Registered displays: DueLCD01, DueLCD02
 */

#ifndef DISPLAY_CONFIG_H
#define DISPLAY_CONFIG_H

#include <Arduino.h>
#include "DisplayManager.h"

// Number of registered displays
#define NUM_DISPLAYS 2


// ========== DueLCD01 ==========
#define DUELCD01_INDEX 0

// Device Information
#define DUELCD01_NAME "DueLCD01"
#define DUELCD01_MANUFACTURER "Unknown"
#define DUELCD01_MODEL "Generic ST7735"

// Pin Assignments
#define DUELCD01_TFT_CS 7
#define DUELCD01_TFT_DC 10
#define DUELCD01_TFT_RST 8
#define DUELCD01_TFT_BL 9

// Display Dimensions
#define DUELCD01_DISPLAY_WIDTH 160
#define DUELCD01_DISPLAY_HEIGHT 128
#define DUELCD01_DISPLAY_ROTATION 1

// Calibrated Usable Area
#define DUELCD01_USABLE_ORIGIN_X 1
#define DUELCD01_USABLE_ORIGIN_Y 2
#define DUELCD01_USABLE_WIDTH 158
#define DUELCD01_USABLE_HEIGHT 126

// Center Point
#define DUELCD01_CENTER_X 80
#define DUELCD01_CENTER_Y 65

// ========== DueLCD02 ==========
#define DUELCD02_INDEX 1

// Device Information
#define DUELCD02_NAME "DueLCD02"
#define DUELCD02_MANUFACTURER "Jessinie"
#define DUELCD02_MODEL "n/a"

// Pin Assignments
#define DUELCD02_TFT_CS 29
#define DUELCD02_TFT_DC 31
#define DUELCD02_TFT_RST 33
#define DUELCD02_TFT_BL 35

// Display Dimensions
#define DUELCD02_DISPLAY_WIDTH 128
#define DUELCD02_DISPLAY_HEIGHT 160
#define DUELCD02_DISPLAY_ROTATION 0

// Calibrated Usable Area
#define DUELCD02_USABLE_ORIGIN_X 2
#define DUELCD02_USABLE_ORIGIN_Y 1
#define DUELCD02_USABLE_WIDTH 126
#define DUELCD02_USABLE_HEIGHT 158

// Center Point
#define DUELCD02_CENTER_X 65
#define DUELCD02_CENTER_Y 80

// Display Registry Initialization
inline void initializeDisplayRegistry(DisplayManager& manager) {

    // Add DueLCD01
    {
        DisplayConfig cfg;
        cfg.name = DUELCD01_NAME;
        cfg.manufacturer = DUELCD01_MANUFACTURER;
        cfg.model = DUELCD01_MODEL;
        cfg.cs = DUELCD01_TFT_CS;
        cfg.dc = DUELCD01_TFT_DC;
        cfg.rst = DUELCD01_TFT_RST;
        cfg.bl = DUELCD01_TFT_BL;
        cfg.width = DUELCD01_DISPLAY_WIDTH;
        cfg.height = DUELCD01_DISPLAY_HEIGHT;
        cfg.rotation = DUELCD01_DISPLAY_ROTATION;
        cfg.usableX = DUELCD01_USABLE_ORIGIN_X;
        cfg.usableY = DUELCD01_USABLE_ORIGIN_Y;
        cfg.usableWidth = DUELCD01_USABLE_WIDTH;
        cfg.usableHeight = DUELCD01_USABLE_HEIGHT;
        cfg.centerX = DUELCD01_CENTER_X;
        cfg.centerY = DUELCD01_CENTER_Y;
        manager.addDisplay(cfg);
    }

    // Add DueLCD02
    {
        DisplayConfig cfg;
        cfg.name = DUELCD02_NAME;
        cfg.manufacturer = DUELCD02_MANUFACTURER;
        cfg.model = DUELCD02_MODEL;
        cfg.cs = DUELCD02_TFT_CS;
        cfg.dc = DUELCD02_TFT_DC;
        cfg.rst = DUELCD02_TFT_RST;
        cfg.bl = DUELCD02_TFT_BL;
        cfg.width = DUELCD02_DISPLAY_WIDTH;
        cfg.height = DUELCD02_DISPLAY_HEIGHT;
        cfg.rotation = DUELCD02_DISPLAY_ROTATION;
        cfg.usableX = DUELCD02_USABLE_ORIGIN_X;
        cfg.usableY = DUELCD02_USABLE_ORIGIN_Y;
        cfg.usableWidth = DUELCD02_USABLE_WIDTH;
        cfg.usableHeight = DUELCD02_USABLE_HEIGHT;
        cfg.centerX = DUELCD02_CENTER_X;
        cfg.centerY = DUELCD02_CENTER_Y;
        manager.addDisplay(cfg);
    }

}

#endif // DISPLAY_CONFIG_H
